
jobs:
- name: mirror_local
  type: local
  # snapshot the filesystems matched by the left-hand-side of the mapping
  # every 10m with zrepl_ as prefix
  replication:
    filesystems: {
      "pool1/var/db<": true,
      "pool1/usr/home<": true,
      "pool1/usr/home/paranoid": false, #don't backup paranoid user
      "pool1/poudriere/ports<": false #don't backup the ports trees
    }
    # TODO FIXME enforce that the tree under root_dataset and the trees allowed (true) by filesystems are non-overlapping
    root_dataset: "pool2/backups/pool1"

  snapshotting:
    snapshot_prefix: zrepl_
    interval: 10m

  pruning:
    keep_sender:
    - type: not_replicated
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d
      keep_bookmarks: all

global:
  logging:
  - type: "stdout"
    time: true
    level: "warn"
    format: "human"
  monitoring:
  - type: "prometheus"
    listen: ":9091"
  control:
    sockpath: /var/run/zrepl/control
  serve:
    stdinserver:
      sockdir: /var/run/zrepl/stdinserver
