jobs:

- name: pull_servers
  type: pull
  replication:
    connect:
      type: ssh+stdinserver
      host: app-srv.example.com
      user: root
      port: 22
      identity_file: /etc/zrepl/ssh/identity
      options: # optional, default [], `-o` arguments passed to ssh
      - "Compression=on"
    root_dataset: "pool2/backup_servers"
  pruning:
    keep_sender:
    - type: not_replicated
    - type: last_n
      count: 10
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 14x1d
      keep_bookmarks: all
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d
      keep_bookmarks: all

global:
  logging:
  - type: "stdout"
    time: true
    level: "warn"
    format: "human"
  monitoring:
  - type: "prometheus"
    listen: ":9091"
  control:
    sockpath: /var/run/zrepl/control
  serve:
    stdinserver:
      sockdir: /var/run/zrepl/stdinserver