type: sink
replication:
  root_dataset: "pool2/backup_laptops"
  serve:
    type: tls
    listen: "192.168.122.189:8888"
    ca: "ca.pem"
    cert: "cert.pem"
    key: "key.pem"
global:
  logging:
    - outlet:
        type: "syslog"
      level: "warn"
      format: "human"
