jobs:
- name: mirror_local
  type: local

  # snapshot the filesystems matched by the left-hand-side of the mapping
  # every 10m with zrepl_ as prefix
  mapping: {
    "zroot/var/db<":    "storage/backups/local/zroot/var/db",
    "zroot/usr/home<":  "storage/backups/local/zroot/usr/home",
  }
  snapshot_prefix: zrepl_
  interval: 10m
  initial_repl_policy: most_recent

  # keep one hour of 10m interval snapshots of filesystems matched by
  # the left-hand-side of the mapping
  prune_lhs:
    policy: grid
    grid: 1x1h(keep=all)

  # follow a grandfathering scheme for filesystems on the right-hand-side of the mapping
  prune_rhs:
    policy: grid
    grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d


