# push backup to backups.example.com
backups.example.com:

  connect:
    type: ssh
    host: 192.168.122.128
    user: root
    port: 22
    identity_file: /root/.ssh/id_ed25519
    connlog_read_file: /tmp/connlog_read
    connlog_write_file: /tmp/connlog_write

  global:
    snapshot_prefix: zrepl_

  schedule:
    type: auto

  steps:

    # take local snapshots & keep window of one day
    - type: autosnap
      interval: 10m
      dataset_filter: {
        "zroot/var/db<": ok,
        "zroot/usr/home<": ok,
      }
    - type: prune
      policy: grid
      grid: 1x1d(keep=all)
      dataset_filter: {
        "zroot/var/db<":  ok,
        "zroot/usr/home<": ok,
      }

    # push datasets to remote and prune there
    # if these jobs fail, we have one day until we are out of sync
    - type: push
      dataset_filter: {
        "zroot/var/db<":   ok,
        "zroot/usr/home<": ok,
      }
    - type: prune
      remote: true
      policy: grid
      grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d

