jobs:
- name: fullbackup_prod1

  # connect to remote using ssh / stdinserver command
  type: push
  connect:
      type: ssh+stdinserver
      host: prod1.example.com
      user: root
      port: 22
      identity_file: /root/.ssh/id_ed25519

  # snapshot these datsets every 10m with zrepl_ as prefix
  datasets: {
    "zroot/var/db<": "ok",
    "zroot/usr/home<": "!",
  }
  snapshot_prefix: zrepl_
  interval: 10m

  # keep a one day window 10m interval snapshots in case push doesn't work (link down, etc)
  # (we cannot keep more than one day because this host will run out of disk space)
  prune:
    policy: grid
    grid: 1x1d(keep=all)

