global:
  serve:
    stdinserver:
      sockdir: /var/run/zrepl/stdinserver

jobs:

- name: debian2_pull
  # JOB DEBUGGING OPTIONS
  # should be equal for all job types, but each job implements the debugging itself
  # => consult job documentation for supported options
  debug:
    conn: # debug the io.ReadWriteCloser connection
      read_dump: /tmp/connlog_read   # dump results of Read() invocations to this file
      write_dump: /tmp/connlog_write # dump results of Write() invocations to this file
    rpc: # debug the RPC protocol implementation
      log: true # log output from rpc layer to the job log

  # ... just to make the unit tests pass.
  # check other examples, e.g. localbackup or pullbackup for what the sutff below means
  type: source
  serve:
    type: stdinserver
    client_identity: debian2
  datasets: {
    "pool1/db<": ok
  }
  snapshot_prefix: zrepl_
  interval: 1s
  prune:
    policy: grid
    grid: 1x10s(keep=all)

