jobs:
  - type: sink
    name: "laptop_sink"
    root_dataset: "pool2/backup_laptops"
    serve:
      type: tls
      listen: "192.168.122.189:8888"
      ca: "ca.pem"
      cert: "cert.pem"
      key: "key.pem"
      client_cn: "laptop1"
global:
  logging:
    - type: "tcp"
      address: "123.123.123.123:1234"
      retry_interval: 10s
      tls:
        ca: "ca.pem"
        cert: "cert.pem"
        key: "key.pem"
      level: "warn"
      format: "human"
  control:
    sockpath: /var/run/zrepl/control
  serve:
    stdinserver:
      sockdir: /var/run/zrepl/stdinserver