jobs:
- name: pull_source
  type: source
  serve:
    type: stdinserver
    client_identities:
      - "client1"
      - "client2"
  filesystems: {
    "<": true,
    "secret": false
  }
  snapshotting:
    snapshot_prefix: zrepl_
    interval: 10m
