jobs:
- name: fullbackup_prod1
  type: pull
  # connect to remote using ssh / stdinserver command
  connect:
    type: ssh+stdinserver
    host: prod1.example.com
    user: root
    port: 22
    identity_file: /root/.ssh/id_ed25519

  # pull (=ask for new snapshots) every 10m, prune afterwards
  # this will leave us at most 10m behind production
  interval: 10m

  # pull all offered filesystems to storage/backups/zrepl/pull/prod1.example.com
  mapping: {
    "<":"storage/backups/zrepl/pull/prod1.example.com"
  }

  # follow a grandfathering scheme for filesystems on the right-hand-side of the mapping
  snapshot_prefix: zrepl_
  prune:
    policy: grid
    grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d

