fullbackup_prod1:

  # expect remote to connect via ssh+stdinserver with fullbackup_prod1 as client_identity
  type: pull-source
  serve:
    type: stdinserver
    client_identity: fullbackup_prod1

  # snapshot these filesystems every 10m with zrepl_ as prefix
  datasets: {
    "zroot/var/db<": ok,
    "zroot/usr/home<": omit,
  }
  snapshot_prefix: zrepl_
  interval: 10m

  # keep a one day window 10m interval snapshots in case pull doesn't work (link down, etc)
  # (we cannot keep more than one day because this host will run out of disk space)
  prune:
    policy: grid
    grid: 1x1d(keep=all)

